algoritmo "EstoqueMedio"
// Função : Calculae o Estoque Médio
// Autor :  Beatriz dos Santos Silva
// Data : 05/03/2018
// Seção de Declarações 
var
qtdemin:real
qtdemax:real
estoquemedio:real
inicio
escreval ("Insira aqui a Quantidade Mínima: ")
leia(qtdemin)
escreval ("Insira aqui a Quantidade Máxima: ")
leia (qtdemax)
estoquemedio <- (qtdemin+qtdemax)/2
escreva ("O Estoque Médio é de: ",estoquemedio)
fimalgoritmo
