algoritmo "AreaTriânguloRetângulo"
// Função : Calcular a área do triângulo retângulo
// Autor :  Beatriz dos Santos Silva
// Data : 26/02/2018
// Seção de Declarações 
var
base:real
altura:real
area:real
inicio
escreval ("Digite aqui a base do triângulo: ")
leia (base)
escreval ("Digite aqui a altura do triângulo: ")
leia (altura)
area <- base*altura/2
escreva ("A área do Triângulo Retângulo é: ", area)
fimalgoritmo
