algoritmo "Área do Retângulo"
// Função : Fornecer a área do retângulo
// Autor :  Beatriz Silva
// Data : 26/02/2018
// Seção de Declarações 
var
base:real
altura:real
area:real
inicio
escreval ("Digite aqui a base do retângulo: ")
leia (base)
escreval ("Digite aqui a altura do retângulo: ")
leia (altura)
area <- base*altura
escreva ("A área do retângulo é: ", area)
fimalgoritmo
