algoritmo "Soma"
// Função :
// Autor :
// Data : 30/07/2018
// Seção de Declarações 
var
X, Y: inteiro
Procedimento Soma(A, B: inteiro)
inicio
escreval ("Recebi o valor", A)
escreval ("Recebi o valor", B)
escreval ("A soma entre os dois é ", A+B)
fimprocedimento
inicio
escreval ("Digite um valor para X ")
leia (X)
escreval ("Digite um valor para Y ")
leia (Y)
Soma(X, Y)
fimalgoritmo
