algoritmo "SomaFuncao"
// Função :
// Autor :
// Data : 06/08/2018
// Seção de Declarações 
funcao Soma(X, Y: inteiro) : inteiro
inicio
Retorne X + Y
fimfuncao
var
V1, V2: inteiro
S: inteiro
inicio
escreval ("Digite o primeiro valor ")
leia (V1)
escreval ("Digite o segundo valor ")
leia (V2)
S <- Soma(V1, V2)
escreval ("A soma entre ", V1, " e", V2, " é igual a ", S)
fimalgoritmo
