algoritmo "Volume da Esfera"
// Função : Recebe por parâmetro o raio de uma esfera e calcula o seu volume.
// Autor : Beatriz dos Sanos Silva
// Data : 30/07/2018
// Seção de Declarações 
var
r: inteiro
Procedimento Volume (A: inteiro)
inicio
escreval (" O Volume da Esfera é ", 4/3*3.14*r^3)
fimprocedimento
inicio
escreval ("Digite aqui o valor do Raio da esfera: ")
leia (r)
Volume(r)
fimalgoritmo
