algoritmo "Número Inicial e Final"
// Função : Escreve na tela os números de um número inicial a um número final. Os números inicial e final devem ser informados pelo usuário;
// Autor : Beatriz dos Santos Silva
// Data : 25/06/2018
// Seção de Declarações 
var
numi, numf:inteiro
cont: inteiro
inicio
escreval ("Digite aqui o número inicial ")
leia (numi)
escreval ("Digite aqui o número Final ")
leia (numf)

para cont de numi ate numf faca
escreval (cont)
fimpara
fimalgoritmo
