algoritmo "Soma 10 números"
// Função : Lê 10 números inteiros e, ao final, apresenta a soma de todos os números lidos
// Autor :  Beatriz dos Santos Silva
// Data : 25/06/2018
// Seção de Declarações 
var
num, numsoma: inteiro
inicio
para num de 1 ate 10 passo 1 faca
escreval ("Digite aqui um número inteiro ")
leia (num)
numsoma <- numsoma+num
fimpara

escreval (numsoma)

fimalgoritmo
