algoritmo "Intervalo"
// Função :  Solicita um número e diz de ele está no intervalo de 100 a 200
// Autor :   Beatriz dos Santos Silva
// Data : 14/05/2018
// Seção de Declarações 
var
num:inteiro
inicio
escreval ("Digite aqui um número de sua escolha: ")
leia (num)

se (num>=100) e (num<=200) entao
escreval ("O número está no intervalo entre 100 e 200 ")

senao
escreval ("O número não está no intervalo entre 100 e 200 ")
fimse
fimalgoritmo
